export const inputSearchEl = document.querySelector('#search')
export const resultSearchLengthEl = document.querySelector('#search-length')
export const resultSearchEl = document.querySelector('#search-result')
export const tableHeds = document.getElementsByTagName('th')
export const tableDatas = document.getElementsByTagName('td')