import {invertString} from "./functions.js"

export const dictionary = {
    "IPPIII": "deus",
    "IIIPII": "diabo",
    "PPIPPP": "cruz",
    "IPIIIP": "enigma",
    "PPPPIP": "cabala",
    "PIIIPP": "abracadabra",
    "IPPPPI": "adivinhacao",
    "IIIIPP": "criatividade",
    "PIIPIP": "maldicao",
    "PPIPIP": "bencao",
    "IIIPIP": "verdade",
    "PPPIIP": "mentira",
    "PPPIPP": "sabio",
    "IIPPIP": "loucura",
    "PIIPPP": "felicidade",
    "PIIPII": "tristeza",
    "PIIIPI": "genio",
    "PIPIIP": "esperto",
    "PPPPPI": "anjo",
    "PPIIII": "mistico",
    "PIPIPP": "curioso",
    "IPPIPI": "abobalhado",
    "IIPPII": "ignorante",
    "IPPPPP": "santo",
    "IIIIPI": "extraordinario",
    "IIPIPP": "revolucionario",
    "IIPIII": "filosofo",
    "PPIPPI": "mestre",
    "PPPPII": "vencedor",
    "IPIIII": "exigente",
    "IPIPPI": "digno",
    "PIPPPI": "clarividente",
    "IIIIII": "profecia",
    "PIPIII": "sabedoria",
    "IPIPII": "justica",
    "PIIIII": "honra",
    "IPPIPP": "amor",
    "IIPIPI": "fe",
    "PPIIIP": "esperanca",
    "PIPIPI": "dom",
    "IIIPPI": "personalidade",
    "IIPIIP": "perseveranca",
    "PIPPII": "persistencia",
    "IPIPIP": "paciencia",
    "IIIPPP": "consciencia",
    "PIIPPI": "inteligencia",
    "IIPPPI": "independencia",
    "PPIIPP": "indiferenca",
    "IPPIIP": "inveja",
    "PIIIIP": "injustica",
    "PPIPII": "preguica",
    "PPPIII": "maldade",
    "IPPPII": "profano",
    "PIPPIP": "corrupto",
    "PPPPPP": "infidelidade",
    "PIPPPP": "individualista",
    "IIIIIP": "verdadeiro",
    "IIPPPP": "falso",
    "IPIIPP": "obediencia",
    "IPIIPI": "infelicidade",
    "PPIIPI": "bem",
    "IPPPIP": "notavel",
    "PPPIPI": "profissionalmente",
    "IPIPPP": "proporcionalmente"
}

export const gematria = 'abcdefghijklmnopqrstuvwxyz'
export const gematriaInverse = invertString(gematria)